#!/usr/bin/env node
/**
 * Sets up an embedded Python interpreter (python-build-standalone) and
 * installs the required packages for the MCP server.
 *
 * Outputs:
 *   src-tauri/resources/python/    ← portable CPython distribution
 *   .cargo/config.toml             ← points PYO3_PYTHON at the bundled interpreter
 *
 * Run: node scripts/setup-python.js
 */

import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync, readFileSync, copyFileSync, unlinkSync, createWriteStream } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import https from 'node:https';
import os from 'node:os';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');
const srcTauriDir = join(projectRoot, 'src-tauri');
const resourcesDir = join(srcTauriDir, 'resources');
const pythonDir = join(resourcesDir, 'python');

// ── Version pins ────────────────────────────────────────────────────────────
const PYTHON_VERSION = '3.12.10';
const BUILD_DATE = '20250409';    // release tag on astral-sh/python-build-standalone

// ── Platform detection ───────────────────────────────────────────────────────
function getPlatformTriple() {
  const p = os.platform();
  const a = os.arch();
  if (p === 'win32')  return a === 'x64' ? 'x86_64-pc-windows-msvc'       : 'i686-pc-windows-msvc';
  if (p === 'linux')  return a === 'x64' ? 'x86_64-unknown-linux-gnu'      : 'aarch64-unknown-linux-gnu';
  if (p === 'darwin') return a === 'arm64' ? 'aarch64-apple-darwin'        : 'x86_64-apple-darwin';
  throw new Error(`Unsupported platform: ${p} ${a}`);
}

function getPythonExe() {
  return os.platform() === 'win32'
    ? join(pythonDir, 'python.exe')
    : join(pythonDir, 'bin', 'python3.12');
}

// ── Download helpers ─────────────────────────────────────────────────────────
async function downloadFile(url, dest) {
  return new Promise((resolve, reject) => {
    const follow = (u) => {
      https.get(u, (res) => {
        if (res.statusCode === 301 || res.statusCode === 302) {
          return follow(res.headers.location);
        }
        if (res.statusCode !== 200) {
          return reject(new Error(`HTTP ${res.statusCode} downloading ${u}`));
        }
        const f = createWriteStream(dest);
        res.pipe(f);
        f.on('finish', () => { f.close(); resolve(); });
        f.on('error', reject);
      }).on('error', reject);
    };
    follow(url);
  });
}

function extractTarGz(tarPath, destDir) {
  mkdirSync(destDir, { recursive: true });
  
  if (os.platform() === 'win32') {
    // Windows tar often chokes on drive letters (C:\) because it thinks it's a remote host.
    // We'll copy the file to the destination dir temporarily to use a relative path.
    const tmpTarName = 'bundle.tar.gz';
    const tmpTarPath = join(destDir, tmpTarName);
    copyFileSync(tarPath, tmpTarPath);
    try {
      execSync(`tar -xzf ${tmpTarName} --strip-components=1`, { 
        stdio: 'inherit', 
        cwd: destDir 
      });
    } finally {
      if (existsSync(tmpTarPath)) unlinkSync(tmpTarPath);
    }
  } else {
    // Unix tar is well-behaved.
    execSync(`tar -xzf "${tarPath}" -C "${destDir}" --strip-components=1`, { stdio: 'inherit' });
  }
}

// ── Write .cargo/config.toml so PyO3 finds the bundled interpreter ───────────
function writeCargoConfig() {
  const cargoDir = join(projectRoot, '.cargo');
  const configPath = join(cargoDir, 'config.toml');
  mkdirSync(cargoDir, { recursive: true });

  const pythonExe = getPythonExe().replace(/\\/g, '/');

  // Preserve any existing sections that are not [env]
  let existing = '';
  if (existsSync(configPath)) {
    existing = readFileSync(configPath, 'utf8')
      .split('\n')
      .filter(l => !l.startsWith('PYO3_PYTHON') && !l.startsWith('[env]'))
      .join('\n')
      .trimEnd();
  }

  const content = `${existing ? existing + '\n\n' : ''}# Auto-generated by scripts/setup-python.js — do not edit the lines below
[env]
PYO3_PYTHON = "${pythonExe}"
`;
  writeFileSync(configPath, content);
  console.log(`✓ Written .cargo/config.toml  →  PYO3_PYTHON = ${pythonExe}`);
}

// ── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  const triple = getPlatformTriple();
  const filename = `cpython-${PYTHON_VERSION}+${BUILD_DATE}-${triple}-install_only.tar.gz`;
  const url = `https://github.com/astral-sh/python-build-standalone/releases/download/${BUILD_DATE}/${filename}`;
  const pythonExe = getPythonExe();

  // ── Download + extract python-build-standalone ───────────────────────────
  if (existsSync(pythonExe)) {
    console.log(`✓ Bundled Python already present: ${pythonExe}`);
  } else {
    console.log(`\nDownloading Python ${PYTHON_VERSION} for ${triple} …`);
    console.log(`  ${url}\n`);

    const tmpFile = join(os.tmpdir(), filename);
    if (!existsSync(tmpFile)) {
      await downloadFile(url, tmpFile);
      console.log('✓ Download complete');
    } else {
      console.log('✓ Using cached download from', tmpFile);
    }

    console.log(`Extracting to ${pythonDir} …`);
    extractTarGz(tmpFile, pythonDir);
    console.log('✓ Extraction complete');
  }

  // ── Write .cargo/config.toml ─────────────────────────────────────────────
  writeCargoConfig();

  // ── Install Python packages ───────────────────────────────────────────────
  console.log('\nInstalling Python packages …');
  execSync(`"${pythonExe}" -m pip install --upgrade pip`, { stdio: 'inherit' });
  execSync(`"${pythonExe}" -m pip install fastmcp`, { stdio: 'inherit' });

  if (os.platform() === 'win32') {
    console.log('\nInstalling Windows-only packages (pywin32) …');
    execSync(`"${pythonExe}" -m pip install pywin32`, { stdio: 'inherit' });
    // pywin32 post-install registers COM servers and copies DLLs
    try {
      execSync(`"${pythonExe}" "${pythonDir}/Scripts/pywin32_postinstall.py" -install`,
               { stdio: 'inherit' });
    } catch (_) {
      console.warn('  pywin32 post-install script not found — you may need to run it manually');
    }
  }

  console.log('\n✅  setup-python complete!\n');
  console.log('Next steps:');
  console.log('  npm run tauri dev       — start the app in dev mode');
  console.log('  npm run tauri build     — build the release installer');
}

main().catch((err) => {
  console.error('\n❌  setup-python failed:', err.message);
  process.exit(1);
});
